// Package policy translates a scan's verdicts into a tapelog policy pack.
//
// This is the bridge between the two halves of the same defence: slopscan says what a server *is*,
// tapelog stops it mid-call. A reviewed scan should not have to be re-typed as policy by hand -
// the verdict already knows which tools destroy things, which ones run commands, and which of them
// carry instructions aimed at the model. Turning that into "deny the dangerous, confirm the risky,
// allow the routine" is transcription, and transcription is what machines are for.
//
// The generated pack is a starting point, not a verdict on its own: it is meant to be read,
// adjusted for the estate it runs in (paths, tables, channels), and validated with tapelog's own
// `policy test` - exactly as the hand-written packs in tapelog's repository are.
package policy

import (
	"fmt"
	"io"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/Caseymccallum/slopscan/internal/injection"
	"github.com/Caseymccallum/slopscan/internal/risk"
)

// Rule is one tapelog policy rule: a tool pattern, an action, and why.
type Rule struct {
	ID     string   `yaml:"id"`
	Tool   []string `yaml:"tool"`
	Action string   `yaml:"action"`
	Reason string   `yaml:"reason"`
}

// Pack is a tapelog policy pack in its file shape (version, default, rules, limits, injection).
type Pack struct {
	Version  int            `yaml:"version"`
	Default  string         `yaml:"default"`
	Rules    []Rule         `yaml:"rules"`
	Limits   map[string]any `yaml:"limits"`
	Injection map[string]any `yaml:"injection"`
}

// Build turns one server's scan into a pack.
//
// The action for each tool is decided by the worst thing known about it:
//
//   - hostile metadata (high-severity injection findings) -> deny. A tool whose description is
//     written for the model rather than the reader is not a tool to run with guardrails; it is a
//     tool to stop.
//   - destructive, financial, execute -> confirm. Legitimate power still deserves a human.
//   - write and anything unrecognised -> confirm. Unknown is not safe.
//   - read, with clean metadata -> allow. The routine case should not need a person.
//
// The default is confirm: an unlisted tool meets a human, not silence.
func Build(serverID, source string, assessments []risk.Assessment, findings map[string][]injection.Finding) Pack {
	pack := Pack{
		Version: 1,
		Default: "confirm",
		Limits: map[string]any{
			"max_calls_per_tool": map[string]any{"*": 25},
			"max_per_minute":     10,
			"max_response_bytes": 262144,
		},
		Injection: map[string]any{"mode": "confirm"},
	}

	for _, assessment := range assessments {
		// A prompt or resource is not a call: tapelog rules govern what an agent invokes, and
		// nothing here can be invoked. The text risks it carries are findings, not rules.
		if assessment.Category == risk.Context {
			continue
		}
		action := "confirm"
		switch {
		case injection.Worst(findings[assessment.Tool]) == "high":
			action = "deny"
		case assessment.Category == risk.Read && len(findings[assessment.Tool]) == 0:
			action = "allow"
		}

		reason := fmt.Sprintf("%s: %s", assessment.Category, strings.Join(assessment.Reasons, "; "))
		if worst := injection.Worst(findings[assessment.Tool]); worst != "" {
			kinds := []string{}
			for _, finding := range findings[assessment.Tool] {
				kinds = append(kinds, finding.Kind+"/"+finding.OWASP)
			}
			reason += " | findings: " + strings.Join(kinds, ", ")
		}

		pack.Rules = append(pack.Rules, Rule{
			ID:     ruleID(assessment.Tool),
			Tool:   []string{assessment.Tool},
			Action: action,
			Reason: reason,
		})
	}

	return pack
}

// ruleID makes a stable, readable rule id from a tool name.
func ruleID(tool string) string {
	id := strings.ToLower(tool)
	id = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			return r
		}
		return '-'
	}, id)
	return "slopscan-" + strings.Trim(id, "-")
}

// Render writes the pack as a policy file, with a header that says where it came from - a
// generated policy that does not name its generator is a policy nobody can re-generate.
func Render(w io.Writer, serverID, source string, pack Pack) error {
	header := fmt.Sprintf(
		"# tapelog policy pack, generated by slopscan from the scan of %q (source: %s).\n"+
			"#\n"+
			"# Generated policy is a starting point: read it, tune it to your estate (paths, tables,\n"+
			"# channels), and validate it like code - tapelog policy test --policy this.yaml --calls samples.jsonl\n"+
			"#\n"+
			"# Philosophy: deny the dangerous, confirm the risky, allow the routine.\n",
		serverID, source,
	)
	if _, err := io.WriteString(w, header); err != nil {
		return err
	}

	encoded, err := yaml.Marshal(pack)
	if err != nil {
		return err
	}
	_, err = w.Write(encoded)
	return err
}