package policy

import (
	"strings"
	"testing"

	"github.com/Caseymccallum/slopscan/internal/injection"
	"github.com/Caseymccallum/slopscan/internal/risk"
)

func TestActionMapping(t *testing.T) {
	assessments := []risk.Assessment{
		{Tool: "read_file", Category: risk.Read, Reasons: []string{"described in read terms (read)"}},
		{Tool: "delete_row", Category: risk.Destructive, Reasons: []string{"described in destructive terms (delete)"}},
		{Tool: "run_cmd", Category: risk.Execute, Reasons: []string{"input schema takes a raw command string"}},
		{Tool: "poisoned", Category: risk.Read, Reasons: []string{"described in read terms (find)"}},
		{Tool: "quiet_read", Category: risk.Read, Reasons: []string{"described in read terms (read)"}},
	}
	findings := map[string][]injection.Finding{
		// Quiet but not hostile: a read tool with one medium oddity still gets confirmed, not
		// denied - only high-severity metadata is treated as hostile.
		"quiet_read": {{Kind: "trigger-phrase", OWASP: "MCP06", Severity: "medium", Quote: "x"}},
		"poisoned":   {{Kind: "instruction-override", OWASP: "MCP03", Severity: "high", Quote: "x"}},
	}

	pack := Build("srv", "test", assessments, findings)
	actions := map[string]string{}
	for _, rule := range pack.Rules {
		actions[rule.Tool[0]] = rule.Action
	}

	if actions["read_file"] != "allow" {
		t.Errorf("clean read got %q, want allow", actions["read_file"])
	}
	if actions["delete_row"] != "confirm" {
		t.Errorf("destructive got %q, want confirm", actions["delete_row"])
	}
	if actions["run_cmd"] != "confirm" {
		t.Errorf("execute got %q, want confirm", actions["run_cmd"])
	}
	if actions["poisoned"] != "deny" {
		t.Errorf("hostile metadata got %q, want deny", actions["poisoned"])
	}
	if actions["quiet_read"] != "confirm" {
		t.Errorf("medium-finding read got %q, want confirm", actions["quiet_read"])
	}
	if pack.Default != "confirm" {
		t.Errorf("default %q, want confirm: an unlisted tool meets a person", pack.Default)
	}
}

// The generated file must carry its provenance and its evidence: a policy nobody can re-generate
// or argue with is a policy nobody should trust.
func TestRenderCarriesProvenanceAndReasons(t *testing.T) {
	pack := Build("srv", "tools.json", []risk.Assessment{
		{Tool: "delete_row", Category: risk.Destructive, Reasons: []string{"described in destructive terms (delete)"}},
	}, map[string][]injection.Finding{
		"delete_row": {{Kind: "exfiltration", OWASP: "MCP01", Severity: "high", Quote: "x"}},
	})

	var out strings.Builder
	if err := Render(&out, "srv", "tools.json", pack); err != nil {
		t.Fatal(err)
	}

	text := out.String()
	for _, want := range []string{
		"generated by slopscan", "srv", "tools.json",
		"deny the dangerous, confirm the risky, allow the routine",
		"slopscan-delete-row", "deny", "destructive", "exfiltration/MCP01",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("rendered pack is missing %q:\n%s", want, text)
		}
	}
}